ONTARIO_CITIES = [
    'barrie', 'belleville', 'brampton', 'brantford', 'burlington', 'chatham', 
    'cornwall', 'dorset', 'grand bend', 'guelph', 'hamilton downtown', 
    'hamilton mountain', 'hamilton west', 'kingston', 'kitchener', 'london', 
    # 'merlin', 
    'milton', 'mississauga', 
    # 'morrisburg', 
    'newmarket', 'north bay', 
    'oakville', 'oshawa', 
    # 'ottawa central', 
    'ottawa downtown', 'parry sound', 
    # 'petawawa', 
    'peterborough', 'port stanley', 'sarnia', 'sault ste. marie', 
    'st. catharines', 
    # 'stouffville', 
    'sudbury', 'thunder bay', 
    # 'thunder bay???', 
    'tiverton', 'toronto downtown', 'toronto east', 'toronto north', 
    'toronto west', 'windsor downtown', 'windsor west',
]

FEDERAL_CITIES = [
    ("ST. JOHN'S", "NEWFOUNDLAND AND LABRADOR"),
    # ("LABRADOR CITY", "NEWFOUNDLAND AND LABRADOR"), 
    # ("CHARLOTTETOWN", "PRINCE EDWARD ISLAND"),
    ("HALIFAX", "NOVA SCOTIA"),
    ("FREDERICTON", "NEW BRUNSWICK"),
    ("MONTRÉAL", "QUEBEC"),
    ("SAGUENAY", "QUEBEC"),
    ("SEPT-ÎLES", "QUEBEC"),
    ("TROIS RIVIÈRES", "QUEBEC"),
    ("QUEBEC", "QUEBEC"),
    ("SHERBROOKE", "QUEBEC"),
    ("OTTAWA", "ONTARIO"),
    ("WINDSOR", "ONTARIO"),
    ("KINGSTON", "ONTARIO"),
    ("TORONTO", "ONTARIO"),
    ("HAMILTON", "ONTARIO"),
    ("SUDBURY", "ONTARIO"),
    ("SAULT STE. MARIE", "ONTARIO"),
    ("THUNDER BAY", "ONTARIO"),
    ("LONDON", "ONTARIO"),
    ("ST. CATHARINES", "ONTARIO"),
    ("NORTH BAY", "ONTARIO"),
    ("BARRIE", "ONTARIO"),
    ("WINNIPEG", "MANITOBA"),
    ("BRANDON", "MANITOBA"),
    ("THOMPSON", "MANITOBA"),
    ("REGINA", "SASKATCHEWAN"),
    ("SASKATOON", "SASKATCHEWAN"),
    ("PRINCE ALBERT", "SASKATCHEWAN"),
    ("EDMONTON", "ALBERTA"),
    ("CALGARY", "ALBERTA"),
    ("LETHBRIDGE", "ALBERTA"),
    ("FORT MCMURRAY", "ALBERTA"),
    ("GRANDE PRAIRIE", "ALBERTA"),
    ("HINTON", "ALBERTA"),
    ("METRO VAN - VANCOUVER", "BRITISH COLUMBIA"),
    ("PRINCE GEORGE", "BRITISH COLUMBIA"),
    ("VICTORIA", "BRITISH COLUMBIA"),
    ("KELOWNA", "BRITISH COLUMBIA"),
    ("KAMLOOPS", "BRITISH COLUMBIA"),
    ("NANAIMO", "BRITISH COLUMBIA"),
    ("FORT ST. JOHN", "BRITISH COLUMBIA"),
    ("WHITEHORSE", "YUKON"),
    ("YELLOWKNIFE", "NORTHWEST TERRITORIES"),
    ("IQALUIT", "NUNAVUT"),
]

FEDERAL_LOCATION_IDS = {  # OpenAQ
    "St. John's": None,
    "Halifax": 774,
    "Fredericton": 8132,
    "Montréal": 8702,
    "Quebec": 491,
    "Sherbrooke": 1195254,
    "Saguenay": 236026,
    "Trois Rivières": 268867,
    "Ottawa": 1275379,
    "Windsor": 1275380,
    "Kingston": 8652,
    "Toronto": 7570,
    "Hamilton": 1206909,
    "Sudbury": 8867,
    "Sault Ste. Marie": 1275800,
    "Thunder Bay": 1274948,
    "London": 1535,
    "St. Catharines": 1275801,
    "North Bay": 1289474,
    "Barrie": 1365266,
    "Winnipeg": 1381,
    "Brandon": None,
    "Thompson": None,
    "Regina": 589,
    "Saskatoon": 958,
    "Prince Albert": 8717,
    "Edmonton": 277971,
    "Calgary": 571,
    "Lethbridge": 537,
    "Fort Mcmurray": 490,
    "Grande Prairie": 277980,
    "Hinton": 277984,
    "Metro Van - Vancouver": 1709,
    "Prince George": 2272,
    "Victoria": 1513,
    "Kamloops": 8644,
    "Kelowna": 230097,
    "Nanaimo": 268737,
    "Fort St. John": 8567,
    "Whitehorse": 224177,
    "Yellowknife": None,
    "Iqaluit": None,
}
