ONTARIO_CITIES = [
    'barrie', 'belleville', 'brampton', 'brantford', 'burlington', 'chatham', 
    'cornwall', 'dorset', 'grand bend', 'guelph', 'hamilton downtown', 
    'hamilton mountain', 'hamilton west', 'kingston', 'kitchener', 'london', 
    # 'merlin', 
    'milton', 'mississauga', 
    # 'morrisburg', 
    'newmarket', 'north bay', 
    'oakville', 'oshawa', 
    # 'ottawa central', 
    'ottawa downtown', 'parry sound', 
    # 'petawawa', 
    'peterborough', 'port stanley', 'sarnia', 'sault ste. marie', 
    'st. catharines', 
    # 'stouffville', 
    'sudbury', 'thunder bay', 
    # 'thunder bay???', 
    'tiverton', 'toronto downtown', 'toronto east', 'toronto north', 
    'toronto west', 'windsor downtown', 'windsor west',
]